// Docs: https://en.cppreference.com/w/cpp/header/random

#include <iostream>
#include <stdio.h>
#include <string>
#include <map>
#include <vector>
#include <algorithm>
#include <random>
using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::map;
using std::sort;
using std::reverse;
using std::mt19937;
using std::random_device;
using std::uniform_int_distribution;

int main() {
    // Will be used to obtain a seed for the random number engine.
    std::random_device rd;

    // Standard mersenne_twister_engine seeded with rd().
    std::mt19937 gen(rd());

    // Use dice to transform the random unsigned 
    // int generated by gen into an int in [1, 6].
    std::uniform_int_distribution<> dice(1, 6);

    for (int n=0; n<10; ++n) {
        std::cout << dice(gen) << "";
        std::cout << "\n";
    }
}